apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sticker-api
  namespace: observabilidad
spec:
  ingressClassName: nginx
  rules:
    - host: sticker-api.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sticker-api
                port:
                  number: 8000
