apiVersion: v1
kind: Secret
metadata:
  name: observabilidad-secrets
  namespace: observabilidad
type: Opaque
data:
  NEW_RELIC_LICENSE_KEY: cmVwbGFjZV9tZQ==
  POSTGRES_PASSWORD: c3RpY2tlcnNfcGFzcw==
