apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
  namespace: observabilidad
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS stickers (
        id SERIAL PRIMARY KEY,
        nombre VARCHAR(100) NOT NULL,
        pais VARCHAR(50) NOT NULL,
        numero INTEGER NOT NULL,
        rareza VARCHAR(20) CHECK (rareza IN ('comun', 'raro', 'legendario')),
        coleccionado BOOLEAN DEFAULT FALSE,
        numero_album INTEGER NOT NULL
    );
