apiVersion: v1
kind: Service
metadata:
  name: sticker-api
  namespace: observabilidad
spec:
  type: ClusterIP
  selector:
    app: sticker-api
  ports:
    - name: http
      port: 8000
      targetPort: 8000
